parameters:
#    acme_teacher.example.class: Acme\TeacherBundle\Example

services:
#    acme_teacher.example:
#        class: %acme_teacher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
